# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Gregory Ditzler
tagline:             'Applied Maching Learning, Computational Intelligence, and Life Science'
description:         'A blog about machine learning and its applications in the life sciences.'
url:                 http://gregoryditzler@gmail.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Gregory Ditzler
  url:               https://twitter.com/gregory_ditzler
  email:             gregory.ditzler@gmail.com

# Custom vars
version:             1.0.0
