---
title: "About Me"
---

```{r fig.width=2, fig.height=2,echo=FALSE}
library(png)
library(grid)
img <- readPNG("greg5.png")
 grid.raster(img)
```

I am an Associate Professor in the [Department of Electrical and Computer Engineering](https://ece.engineering.arizona.edu/){target="_blank"} at [The University of Arizona](http://www.arizona.edu/){target="_blank"}, where I perform research in data mining and applied machine learning (check out my [ECE faculty profile video](https://www.youtube.com/watch?v=Mxx785C3Law)). 


## Education 

| Degree | Institution | Dates |
| --- | ----------- |---|
| __PhD__ | [Drexel University](https://drexel.edu/){target="_blank"} | 2015 |
| __MSc__ | [Rowan University](http://rowan.edu/){target="_blank"} |2011 |
| __BSc__ | [The Pennsylvania College of Technology](https://www.pct.edu/){target="_blank"} | 2008 |


## Employment  

| Position | Location | Dates |
| ---- | ----------- |---|
| Associate Professor | [University of Arizona](https://arizona.edu/){target="_blank"}  | 2021--Preset |
| Assistant Professor |   | 2015--2021 |
| Graduate Research Assistant | [Drexel University](https://drexel.edu/){target="_blank"}  |2011--2015 |
| Research Intern | [AT&T Research Labs](https://about.att.com/sites/labs_research){target="_blank"} | 2013 |
| Adjunct Professor | [Rowan University](https://www.rowan.edu/){target="_blank"} |2010--2015 |
| Graduate Research Assistant | [Rowan University](https://www.rowan.edu/){target="_blank"} |2009--2011 |
| Electronics Systems Engineer | [QorTek, Inc.](https://qortek.com/){target="_blank"} | 2009 |



## Current Funding 
- [Hormonal Response to Infant Caregiving: A Novel Strategy to Break the Opioid Relapse Cycle During the Postpartum Period](https://grantome.com/grant/NIH/DP2-HD105541-01){target="_blank"}, <br/>
   Role: Senior Personnel,  <br/>
   Amount: $2,300,000  <br/>
   Sponsor: __National Institues of Health__ 
- Tactical Cyber Immune System  <br/>
   Role: Principal Investigator  <br/>
   Amount: $200,000  <br/>
   Sponsor: __Army Research Office STTR Phase II__ 
- [REU Site: CAT Vehicle: The Cognitive and Autonomous Test Vehicle](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1950359){target="_blank"}  <br/>
   Role: Co-Investigator,  <br/>
   Amount: $415,000,  <br/>
   Sponsor: __National Science Foundation__ 
- [CAREER: Learning in Adversarial and Nonstationary Environments](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1943552&HistoricalAwards=false){target="_blank"}  <br/>
   Role: Principal Investigator,  <br/>
   Amount: $500,000,  <br/>
   Sponsor: __National Science Foundation__ 
- AMAP-based Autonomic Security Operations Center  <br/>
   Role: Co-Investigator  <br/>
   Amount: $200,000  <br/>
   Sponsor: __Air Force Research Lab SBIR Phase II__ 
- [PACT: Partnership for Proactive Cybersecurity Training](https://www.energy.gov/nnsa/nnsa-minority-serving-institution-partnership-program){target="_blank"}  <br/> 
   Role: Co-Investigator  <br/>
   Amount: $3,000,000  <br/>
   Sponsor: __Department of Energy__ 

## Previous Funding 
- [Doctoral Symposium at the IEEE International Conference on Autonomic Computing](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1907321&HistoricalAwards=false){target="_blank"}  <br/>
  Role: Principal Investigator  <br/>
  Amount: $15,000  <br/>
  Sponsor: __National Science Foundation__ 
- [Multi-Layer Anomaly Behavior Analysis (MLABA) Methodology](https://www.sbir.gov/sbirsearch/detail/1516283){target="_blank"} <br/>
  Role: Principal Investigator  <br/>
  Amount: $15k,  <br/>
  Sponsor: __Office of Naval Research STTR Phase I__ 
- Adversarial Threats to Feature Selection  <br/>
  Role: Principal Investigator  <br/>
  Amount: $15,000  <br/>
  Sponsor: __Air Force Office of Scientific Research VFRP__ 
- Techniques to Adjust Computational Trends Involving Changing Data  <br/>
  Role: Principal Investigator  <br/>
  Amount: $54,000  <br/>
  Sponsor: __Office of Naval Research STTR Phase I__ 
- Autonomic Monitoring, Analysis, and Protection  <br/>
  Role: Principal Investigator  <br/>
  Amount: $30,000   <br/>
  Sponsor: __Air Force Office of Scientific Research STTR Phase II__ 
- [Support of the Doctoral Symposium at the IEEE International Conference on Cloud and Autonomic Computing](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1740456&HistoricalAwards=false){target="_blank"}  <br/>
  Role: Principal Investigator  <br/>
  Amount: $15,000  <br/>
  Sponsor: __National Science Foundation__ 
- Tactical Cyber Immune System  <br/>
  Role: Principal Investigator  <br/>
  Amount: $30k <br/>
  Sponsor: __Army Research Office STTR Phase I__ 
- [Analysis of Large Data Sets](https://afsffp.sysplus.com/SFFP/awardees/2016.aspx){target="_blank"}  <br/>
  Role: Principal Investigator  <br/>
  Amount:  $15k  <br/>
  Sponsor: __Air Force Office of Scientific Research SFFP__ 



## Teaching 
- ECE175 - Computer Programming for Engineering Applications [[Sp2016](syllabus/ece175_sp2016.pdf){target="_blank"}, [Fa2016](syllabus/ece175_fa2016.pdf){target="_blank"}] 
- ECE429/529 - Introduction to Digital Signal Processing [[Fa2018](syllabus/ece429529_fa2018.pdf){target="_blank"}, [Fa2020](syllabus/ece429529_fa2020.pdf){target="_blank"}]
- ECE441a/541a - Automatic Control [[Fa2015](syllabus/ece441541_fa2015.pdf){target="_blank"}, [Fa2017](syllabus/ece441541_fa2017.pdf){target="_blank"}, [Fa2019](syllabus/ece441541_fa2019.pdf){target="_blank"}, [Fa2021](syllabus/ece441541_fa2021.pdf){target="_blank"}] 
- ECE523 - Engineering Applications of Machine Learning and Data Analytics  [[Sp2017](syllabus/ece523_sp2017.pdf){target="_blank"}, [Sp2018](syllabus/ece523_sp2018.pdf){target="_blank"}, [Sp2019](syllabus/ece523_sp2019.pdf){target="_blank"}, [Sp2020](syllabus/ece523_sp2020.pdf){target="_blank"}, [Sp2021](syllabus/ece523_sp2021.pdf){target="_blank"}] 


## In the News 
* [UArizona ECE Magazine 2021](https://issuu.com/azengineering/docs/ece_2021magazine){target="_blank"}
* [Lebanon County native receives National Science Foundation award](https://www.pennlive.com/news/2020/07/lebanon-county-native-receives-national-science-foundation-award.html){target="_blank"}
* [Penn College alum honored with NSF award](https://pctoday.pct.edu/penn-college-alum-honored-with-nsf-faculty-award/){target="_blank"}
* [Researchers want to know how bad actors are tricking machine learning](https://edscoop.com/university-arizona-machine-learning-algorithm-research/){target="_blank"}
* [University of Arizona College of Engineering Digest](https://news.engineering.arizona.edu/news/electrical-engineer-trains-computers-distinguish-between-friend-and-foe){target="_blank"}
* [What Can Cyberdefenses Learn from the Human Immune System?](https://www.govtech.com/news/What-Can-Cyberdefenses-Learn-from-the-Human-Immune-System.html){target="_blank"}
* [$3M Grant to Create Cybersecurity Modeled After Human Body](https://ece.engineering.arizona.edu/news-events/3m-grant-create-cybersecurity-modeled-after-human-body){target="_blank"}
* [IEEE Recognizes ECE Professor, Fellow Authors with Outstanding Paper Award](https://ece.engineering.arizona.edu/news-events/ieee-recognizes-ece-professor-fellow-authors-outstanding-paper-award){target="_blank"}
* [Five New Faculty Members Boost Research and Academics](https://ece.engineering.arizona.edu/news-events/five-new-faculty-members-boost-research-and-academics){target="_blank"}




