---
title: "Alumni"
---


## PhD  
- [Heng Liu](https://www.linkedin.com/in/lh5712/){target="_blank"}, PhD (2021)
- [Kuo-Shiuan Peng](https://www.linkedin.com/in/kuo-shiuan-peng-24360567/){target="_blank"}, PhD (2019)


## MSc  
- [Srishti Gupta](https://www.linkedin.com/in/srishtigupta01/){target="_blank"}, MSc (2021)
- [Jiashu Guo](https://www.linkedin.com/in/jiashu-guo/){target="_blank"}, MSc (2018)
- [Zhengzhong Liang](https://www.linkedin.com/in/zhengzhong-liang-095810137/){target="_blank"}, MSc (2018)



## Graduate Interns 
- [Brandon Black](https://www.linkedin.com/in/brandonleeblack/){target="_blank"} (ECE 2019--2020)
- [Sebastian Thiem](https://www.linkedin.com/in/sebastian-thiem-4b25b1159/){target="_blank"} (ECE 2019--2020)
- [Zili Rong](https://www.linkedin.com/in/zili-rong/){target="_blank"} (ECE 2017--2018)
- [Jonathan Gill](https://www.linkedin.com/in/therealjtgill/){target="_blank"} (ECE 2016--2017) 


## Undergraduate @ UArizona
- Drew Howell (CS 2021)
- Eduardo Zambrana (ECE 2020)
- Jack Blake (ECE 2020)
- Javier Cota (ECE 2020/21)
- [Diego Alcantera](https://www.linkedin.com/in/diego-k-alcantara/){target="_blank"} (ECE 2020)
- [Andrew Burger](https://www.linkedin.com/in/andrew-burger-8a628870){target="_blank"} (ECE 2018/19)
- [Noah Thurston](https://www.linkedin.com/in/noah-t-180021b7/){target="_blank"} (ECE 2019)
- Sean Miller (CS/ECE 2017)

## Summer Undergraduate Research Students 

The research experiences for undergraduate students were externally funded by the National Science Foundation and Department of Energy. 

- [Megan Herzog](https://www.linkedin.com/in/megancherzog) (2021; UArizona) ([Summary](https://www.dropbox.com/s/vtzi4jb0cqte3km/PACT2021Abstracts.pdf?dl=0){target="_blank"})
- Joe Liang (2021; UArizona) ([Summary](https://www.dropbox.com/s/vtzi4jb0cqte3km/PACT2021Abstracts.pdf?dl=0){target="_blank"})
- [Audrey Wiseman](https://www.linkedin.com/in/audrey-wiseman-59093a172/) (2021; Wofford College) 
- [Issac Wasserman](https://www.linkedin.com/in/isaac-wasserman-63423715a/) (2021; Haverford College)
- [Sara Roman](https://www.linkedin.com/in/sara-roman-a24855170/) (2021; Kent State University) 
- Sebastian Valencia (2020; UArizona)  ([presentation](https://www.dropbox.com/s/9q8zer4us69sk7o/Team-5-David-VideoPoster-Machine-Learning.mp4?dl=0){target="_blank"})
- [Ulrich Zongo](https://www.linkedin.com/in/ulrich-stephane-zongo/){target="_blank"} (2020; UArizona) ([presentation](https://www.dropbox.com/s/9q8zer4us69sk7o/Team-5-David-VideoPoster-Machine-Learning.mp4?dl=0){target="_blank"})
- Eduardo Zambrana (2020; UArizona) ([presentation](https://www.dropbox.com/s/9q8zer4us69sk7o/Team-5-David-VideoPoster-Machine-Learning.mp4?dl=0){target="_blank"})
- [Calvin Barrett](https://www.linkedin.com/in/calvin-barrett-293296187/){target="_blank"} (2020; Haverford College) ([presentation](https://www.youtube.com/watch?v=VWeaJDeazUc&feature=youtu.be){target="_blank"})
- [Tomo Bessho](https://www.linkedin.com/in/tbessho/){target="_blank"} (2020; University of Nebraska-Lincoln)  ([presentation](https://www.youtube.com/watch?v=vlJAxQZX9xc&feature=emb_title){target="_blank"})




