---
title: "Summary of Contributions"
---


## In Preparation / Under Review  
- Self-Supervised Correlational Monocular Depth Estimation using a Hybrid Network <br/>
  K.-S. Peng, G. Ditzler, and J. Rozenblit<br/>
  submitted to Neural Networks, 2019. 
- Weakly Semi-supervised Joint Semantic Understanding for Segmentation and Depth Estimation<br/>
  K.-S. Peng, G. Ditzler, and J. Rozenblit<br/>
  submitted to Computer Vision and Image Understanding, 2019. 
- Bypassing Temporal Dependency in Adversarial Audio Examples <br/>
  H. Liu and G. Ditzler<br/>
  submitted to IEEE International Conference on Acoustics, Speech and Signal Processing, 2020. 
- A Convolution Neural Network-enabled Pavement Roughness Assessment using Non-calibrated Vehicle Dynamic Responses <br/>
  J.-H. Jeong, H. Jo, and G. Ditzler <br/>
  under revision to Computer-Aided Civil and Infrastructure Engineering, 2019. 
- [Edge-Guided Occlusion Fading Reduction for a Light-Weighted Self-Supervised Monocular Depth Estimation](https://arxiv.org/pdf/1911.11705.pdf) <br/>
  K.-S. Peng, G. Ditzler, and J. Rozenblit<br/>
  submitted to Arxiv, 2019. 
- Data Poisoning Against Filter Feature Selection <br/>
  H. Liu and G. Ditzler<br/>
  in preparation for Information Sciences, 2020. 
- Soft Weight Networks for Few-Shot Learning <br/>
  S. Hess and G. Ditzler<br/>
  in preparation for Neural Networks, 2019. 


## Journals 
- [Learning What We Don't Care About: Regularization with Sacrifical Functions ](https://www.sciencedirect.com/science/article/pii/S0020025519304219?via%3Dihub){target="_blank"} <br/>
  G. Ditzler, S. Miller, and J. Rozenblit <br/>
  Information Sciences, 2019, vol. 496, pp. 198-211. 
- [A Semi-Parallel Framework for Greedy Information-Theoretic Feature Selection](https://www.sciencedirect.com/science/article/pii/S0020025519302865?dgcid=coauthor){target="_blank"} <br/>
  H. Liu and G. Ditzler <br/>
  Information Sciences, 2019, vol. 492, pp. 13-28.
- [Approximate Kernel Reconstruction for Time-Varying Networks](https://biodatamining.biomedcentral.com/articles/10.1186/s13040-019-0192-1){target="_blank"} <br />
  G. Ditzler, N. Bouaynaya, R. Shterenberg, and H. M. Fathallah Shaykh <br/>
  BMC BioData Mining, 2019, vol. 12, no. 9.
- [A Novelty Detector and Extreme Verification Latency Model for Nonstationary Environments](https://ieeexplore.ieee.org/document/8336956/){target="_blank"}<br/>
  R. Razavi-Far, E. Hallaji, M. Saif, and G. Ditzler <br/>
  IEEE Transactions on Industrial Electronics, 2019, vol. 66, no. 1, pp. 561-570. 
- [Weight normalization with spiking neural networks](https://www.sciencedirect.com/science/article/pii/S0893608018302508){target="_blank"}<br/>
  Z. Liang, D. Schwartz, G. Ditzler, and O. Ozan Koyluoglu<br/>
  Neural Networks, 2018, vol. 108, pp. 365-378. 
- [AKRON: An Algorithm for Approximating Sparse Kernel Reconstruction](http://www.sciencedirect.com/science/article/pii/S0165168417303791){target="_blank"}<br/>
  G. Ditzler, N. Bouaynaya, and R. Shterenberg <br />
  Signal Processing, vol. 144, 2018, pp. 265-270.
- [Improvements to Scalable Online Feature Selection Using Bagging and Boosting](http://ieeexplore.ieee.org/document/8065078/){target="_blank"}<br />
  G. Ditzler, J. LaBarck, J. Ritchie, G. Rosen, and R. Polikar<br/>
  IEEE Transactions on Neural Networks and Learning Systems, 2018. vol. 29, no. 9, pp. 4504-4509
- [A Sequential Learning Approach for Scaling up Filter-Based Feature Subset Selection](http://ieeexplore.ieee.org/abstract/document/7926436/){target="_blank"}<br/>
  G. Ditzler, R. Polikar, and G. Rosen<br />
  IEEE Transactions on Neural Networks and Learning Systems, 2018, vol. 29, no. 6, pp. 2530-2544.
- [Fizzy: Feature selection for metagenomics](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0793-8){target="_blank"}<br />
  G. Ditzler, J. Calvin Morrison, Y. Lan, and G. Rosen<br />
  BMC Bioinformatics, 2015, vol 16, no. 358. 
- [Multi-Layer and Recursive Neural Networks for Metagenomic Classification](http://ieeexplore.ieee.org/document/7219432/){target="_blank"}<br />
  G. Ditzler, R. Polikar, and G. Rosen<br />
  IEEE Transactions on Nanobioscience, 2015, vol. 14, no. 6, pp. 608-616.
- [Adaptive strategies for learning in nonstationary environments: a survey](http://ieeexplore.ieee.org/document/7296710/){target="_blank"}<br />
  G. Ditzler, M. Roveri, C. Alippi, and R. Polikar<br />
  IEEE Computational Intelligence Magazine, 2015, vol. 10, no. 4, pp. 12-25.  
- [A bootstrap based Neyman-Pearson test for identifying variable importance](http://ieeexplore.ieee.org/document/6823119/){target="_blank"}<br />
  G. Ditzler, R. Polikar, and G. Rosen<br />
  IEEE Transactions on Neural Networks and Learning Systems, 2015, vol. 26, no. 4, pp. 880-886. 
- [Incremental learning of concept drift from streaming imbalanced data](http://ieeexplore.ieee.org/document/6235959/){target="_blank"}<br />
  G. Ditzler and R. Polikar<br />
  IEEE Transactions on Knowledge & Data Engineering, 2013, vol. 25, no. 10, pp. 2283–2301.
 

## Conferences 
- [Self-Supervised Correlational Monocular Depth Estimation using ResVGG Network](https://www2.ia-engineers.org/icisip2019/){target="_blank"} <br />
  K.S. Peng, G. Ditzler and J. Rozenblit<br />
  International Conference on Intelligent Systems and Image Processing, 2019.
- [Poisoning mRMR with Adversarial Data](https://2019.ieeeicassp.org/){target="_blank"} <br />
  H. Liu and G. Ditzler <br />
  IEEE International Conference on Acoustics, Speech and Signal Processing, 2019.
- [Online Reconfigurable Antenna State Selection based on Thompson Sampling](http://www.conf-icnc.org/2019/){target="_blank"} <br />
  T. Zhao, G. Ditzler, and M. Li <br />
  International Conference on Computing, Networking and Communications, 2019.
- [The Impact of an Adversary in a Language Model](https://ieeexplore.ieee.org/abstract/document/8628894/){target="_blank"} <br />
  Z. Liang and G. Ditzler <br />
  IEEE Symposium Series on Computational Intelligence, 2018.
- [Malicious HTML File Prediction: A Detection and Classification Perspective with Noisy Data](https://ieeexplore.ieee.org/abstract/document/8612855/){target="_blank"} <br />
  S. Hess, P. Satam, G. Ditzler and S. Hariri <br />
  ACS/IEEE International Conference on Computer Systems and Applications, 2018.
- [Nonlinear Brain Tumor Model Estimation with Long Short-Term Memory Neural Networks](https://ieeexplore.ieee.org/abstract/document/8489616/){target="_blank"} <br />
  J. Guo, Z. Liang, E. Scribner, G. Ditzler, N. Bouaynaya and H. Fathallah-Shaykh <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2018.
- [Fine Tuning Lasso in an Adversarial Environment Against Gradient Attacks](https://ieeexplore.ieee.org/abstract/document/8280924/){target="_blank"} <br />
  G. Ditzler and A. Prater <br />
  IEEE Symposium Series on Computational Intelligence, 2017.
- [Speeding Up Joint Mutual Information Feature Selection with an Optimization Heuristic](https://ieeexplore.ieee.org/abstract/document/8280921/){target="_blank"} <br />
  H. Liu and G. Ditzler <br />
  IEEE Symposium Series on Computational Intelligence, 2017.
- [Framework to Support DDDAS Decision” Support Systems: Design Overview](http://ieeexplore.ieee.org/abstract/document/8064150/){target="_blank"} <br />
  G. Ditzler, A. Akoglu, and S. Hariri <br />
  Workshop on InfoSymbiotics: DDDAS Dynamic Data Driven Applications Systems, 2017.
- [A Self-Protection Agent using Error Correcting Output Codes to Secure Computers and Applications](http://ieeexplore.ieee.org/abstract/document/8064054/){target="_blank"}  <br />
  F. de la Pena Montero, S. Hariri, and G. Ditzler <br />
  IEEE International Conference on Cloud and Autonomic Computing, 2017.
- [Autonomic Management of 3D Cardiac Simulations](http://ieeexplore.ieee.org/abstract/document/8064049/){target="_blank"} <br />
  E. Esmaili, A. Akoglu, G. Ditzler, S. Hariri, J. Szep and T. Moukabary <br />
  IEEE International Conference on Cloud and Autonomic Computing, 2017. (best paper award)
- [Fraud Analysis Approaches in the Age of Big Data - A Review of State of the Art](http://ieeexplore.ieee.org/abstract/document/8064067/){target="_blank"} <br />
  S. Makki, R. Haque, Y. Taher, Z. Assaghir, G. Ditzler, M.-S. Hacid and H. Zeineddine <br />
  International Workshop on Autonomic Systems for Big Data Analytics, 2017.
- [A Fast Information-theoretic Approximation of Joint Mutual Information Feature Selection](http://ieeexplore.ieee.org/abstract/document/7966441/?reload=true){target="_blank"} <br />
  H. Liu and G. Ditzler <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2017.
- [The AKRON-Kalman Filter for Tracking Time-Varying Networks](http://ieeexplore.ieee.org/abstract/document/7897268/){target="_blank"} <br />
  V. Carluccio, N. Bouaynaya, G. Ditzler, and H. M. Fathallah Shaykh <br />
  IEEE International Conference on Biomedical and Health Informatics, 2017.
- [A Study of Incremental Spectral Meta-Learning for Nonstationary Environments](http://ieeexplore.ieee.org/abstract/document/7727178/){target="_blank"} <br />
  G. Ditzler   <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2016.
- [Scaling a Neyman-Pearson subset selection approach via heuristics for mining massive data ](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=7008701){target="_blank"}<br />
  G. Ditzler, M. Austen, R, Polikar, and G. Rosen <br />
  IEEE Symposium on Computational Intelligence in Data Mining, 2014. (travel award) 
- [Feature Subset Selection for Inferring Relative Importance of Taxonomy](http://dl.acm.org/citation.cfm?id=2660824){target="_blank"} <br />
  G. Ditzler and G. Rosen <br />
  ACM International Workshop on Big Data in Life Sciences, 2014. (invited and travel award)
- [Domain Adaptation Bounds for Multiple Expert Systems Under Concept Drift](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6889909){target="_blank"} <br />
  G. Ditzler, G. Rosen, and R. Polikar <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2014. (travel award & best student paper) 
- [Incremental learning of new classes with unbalanced data](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6706770){target="_blank"} <br />
  G. Ditzler, G. Rosen, and R. Polikar <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2013.
- [Discounted expert weighting for concept drift](http://ieeexplore.ieee.org/document/6595773/?arnumber=6595773){target="_blank"} <br />
  G. Ditzler, G. Rosen and R. Polikar <br />
  IEEE International Symposium on Computational Intelligence in Dynamic and Uncertain Environments, 2013.
- [Information theoretic feature selection for high dimensional metagenomic data](http://ieeexplore.ieee.org/document/6507749/?arnumber=6507749){target="_blank"} <br />
  G. Ditzler, R. Polikar, and G. Rosen <br />
  IEEE International Workshop on Genomic Signal Processing and Statistics, 2012.
- [A transductive learning algorithm for concept drift](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6252494){target="_blank"} <br />
  G. Ditzler, G. Rosen and R. Polikar <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2012.
- [Determining significance in metagenomics](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6207004){target="_blank"} <br />
  G. Ditzler, R. Polikar and G. Rosen <br />
  IEEE North Eastern Biomedical Engineering Conference, 2012.
- [Forensic identification with environmental samples](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6288265){target="_blank"} <br />
  G. Ditzler, R. Polikar, and G. Rosen   <br />
  IEEE International Conference on Acoustic, Speech and Signal Processing, 2012.
- [Semi-supervised learning in nonstationary environments](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6033578){target="_blank"} <br />
  G. Ditzler and R. Polikar <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2011. (student travel award)
- [Hellinger distance based drift detection algorithm](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5948491){target="_blank"} <br />
  G. Ditzler and R. Polikar  <br />
  IEEE Symposium on Computational Intelligence in Dynamic and Uncertain Environments, 2011.
- [Fusion methods for boosting performance of speaker identification systems](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5774964){target="_blank"} <br />
  G. Ditzler, J. Ethridge, R. Polikar, and R. Ramachandran <br />
  Asia Pacific Conference of Circuits and Systems, 2010.
- [An incremental learning algorithm for nonstationary environments and imbalanced data](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5597278){target="_blank"} <br />
  G. Ditzler, R. Polikar, and N. V. Chawla <br />
  International Conference on Pattern Recognition, 2010.
- [Optimal $\nu$-SVM parameter estimation using multi-objective evolutionary algorithms](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5586029){target="_blank"} <br />
  J. Ethridge, G. Ditzler, and R. Polikar <br />
  IEEE Congress on Evolutionary Computing, 2010.
- [An ensemble-based incremental learning framework for concept drift and class imbalance](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5596764){target="_blank"} <br />
  G. Ditzler and R. Polikar <br />
  IEEE/INNS International Joint Conference on Neural Networks, 2010.
- [Incremental learning of new classes in unbalanced data: Learn++.UDNC](https://link.springer.com/chapter/10.1007/978-3-642-12127-2_4){target="_blank"} <br />
  G. Ditzler, M. Muhlbaier, and R. Polikar <br />
  International Workshop on Multiple Classifier Systems, 2010.



## Book Chapters  
- [Analysis Methods for Shotgun Metagenomics](https://link.springer.com/chapter/10.1007/978-3-319-74974-7_5){target="_blank"} <br />
  S. Woloszynek, Z. Zhao, G. Ditzler, J. R. Price, E. R. Reichenberger, Y. Lan, J. Chen, J. Earl, 
  S. Keshani Langroodi, G. Ehrlich and G. Rosen <br />
  Springer Theoretical and Applied Aspects of Systems Biology, 2018, pp. 71–112.
- [Adaptive classifiers for nonstationary environments](https://onlinelibrary.wiley.com/doi/abs/10.1002/9781119036821.ch7){target="_blank"} <br />
  C. Alippi, G. Boracchi, G. Ditzler, R. Polikar, and M. Roveri <br />
  Contemporary Issues in Systems, Science and Engineering, IEEE/Wiley Press Book Series, 2015.
- [Variable Selection to Improve Classification of Metagenomes](https://link.springer.com/referenceworkentry/10.1007/978-1-4614-6418-1_364-4){target="_blank"} <br />
  G. Ditzler, Y. Lan, J.-L. Bouchot, and G. Rosen <br />
  In: Nelson K. (eds) Encyclopedia of Metagenomics. Springer, New York, NY, 2014. 
- [Advances in machine learning for processing and comparison of metagenomic data](https://app.dimensions.ai/details/publication/pub.1030514139){target="_blank"} <br />
  J.-L. Bouchot, W. Trimble, G. Ditzler, Y. Lan, S. Essinger, and G. Rosen <br />
  In: Computational Systems Biology, 295-329, 2014


