---
title: "Publications"
html-math-method: mathjax
editor: source
---


## Arxiv 
- [PACOL: Poisoning Attacks Against Continual Learners](https://arxiv.org/abs/2311.10919){target="_blank"} <br/>
  H. Li and G. Ditzler <br/>
  arXiv preprint arXiv:2311.10919, 2023.  
- [Sleep Stage Classification with Learning from Evolving Datasets](https://www.techrxiv.org/articles/preprint/Sleep_Stage_Classification_with_Learning_from_Evolving_Datasets/23730546){target="_blank"} <br/>
  H. Li, X. Chen, W. Killmore, S. Quan, G. Ditzler, P. Chang, J. Roveda, and A. Li<br/>
  techrxiv preprint techrxiv.23730546.v1, 2023. 
- [A Maximum Log-Likelihood Method for Imbalanced Few-Shot Learning Tasks](https://arxiv.org/abs/2211.14668){target="_blank"} <br/>
  S. Hess and G. Ditzler <br/>
  arXiv preprint arXiv:2211.14668, 2022. 


## Journals
1. [Stealthy Adversarial Attacks on Machine Learning-Based Classifiers of Wireless Signals](https://ieeexplore.ieee.org/document/10436107){target="_blank"} <br/> 
  W. Zhang, M. Krunz and G. Ditzler <br/>
  IEEE Transactions on Machine Learning in Communications and Networking, 2024, accepted. 
1. [Knowledge Distillation Under Ideal Joint Classifier Assumption](https://arxiv.org/abs/2304.11004){target="_blank"} <br/>
  H. Li, X. Chen, G. Ditzler, P. Chang, J. Roveda, and A. Li <br/>
  Neural Networks, 2024, accepted. ([arXiv:2304.11004](https://arxiv.org/abs/2304.11004){target="_blank"}) 
1. [ProtoShotXAI: Using Prototypical Few-Shot Architecture for Explainable AI](https://jmlr.org/papers/v24/21-1261.html){target="_blank"} <br/>
  S. Hess and G. Ditzler <br/>
  Journal of Machine Learning Research, 24(325):1−49, 2023. 
1. [DeScoD-ECG: Deep Score-Based Diffusion Model for ECG Baseline Wander and Noise Removal](https://arxiv.org/abs/2208.00542){target="_blank"} <br/>
  H. Li, G. Ditzler, J. Roveda and A. Li <br/>
  IEEE Journal of Biomedical and Health Informatics, 2023, accepted. ([arXiv:2208.00542](https://arxiv.org/abs/2208.00542){target="_blank"})
1. [Ovarian Cancer Detection Using Optical Coherence Tomography and Convolutional Neural Networks](https://link.springer.com/article/10.1007/s00521-022-06920-3){target="_blank"} <br/>
  D. Schwartz, T. Sawyer, N. Thurston, J. Barton and G. Ditzler <br/>
  Neural Computing and Applications, vol. 34, no. 11, pp. 8977-8987, 2022. 
1. [Attack Transferability Against Information-Theoretic Feature Selection](https://ieeexplore.ieee.org/document/9514862){target="_blank"} <br/>
  S. Gupta, R. Golota and G. Ditzler <br/>
  IEEE Access, 2021, vol. 9, pp. 115885-115894. 
1. [Data Poisoning Against Information-Theoretic Feature Selection](https://doi.org/10.1016/j.ins.2021.05.049){target="_blank"} <br/>
  H. Liu and G. Ditzler <br/>
  Information Sciences, 2021, vol. 573, pp. 396-411.   
1. [A Convolutional Neural Network-enabled Pavement Roughness Assessment using Non-calibrated Vehicle Dynamic Responses](https://onlinelibrary.wiley.com/doi/abs/10.1111/mice.12546){target="_blank"} <br/>
  J.-H. Jeong, H. Jo, and G. Ditzler <br/>
  Computer-Aided Civil and Infrastructure Engineering, 2020. 
1. [Learning What We Don't Care About: Regularization with Sacrifical Functions](https://www.sciencedirect.com/science/article/pii/S0020025519304219?via%3Dihub){target="_blank"} <br/>
  G. Ditzler, S. Miller, and J. Rozenblit <br/>
  Information Sciences, 2019, vol. 496, pp. 198-211. 
1. [A Semi-Parallel Framework for Greedy Information-Theoretic Feature Selection](https://www.sciencedirect.com/science/article/pii/S0020025519302865?dgcid=coauthor){target="_blank"} <br/>
  H. Liu and G. Ditzler <br/>
  Information Sciences, 2019, vol. 492, pp. 13-28.
1. [Approximate Kernel Reconstruction for Time-Varying Networks](https://biodatamining.biomedcentral.com/articles/10.1186/s13040-019-0192-1){target="_blank"} <br />
  G. Ditzler, N. Bouaynaya, R. Shterenberg, and H. M. Fathallah Shaykh <br/>
  BMC BioData Mining, 2019, vol. 12, no. 9.
1. [A Novelty Detector and Extreme Verification Latency Model for Nonstationary Environments](https://ieeexplore.ieee.org/document/8336956/){target="_blank"}<br/>
  R. Razavi-Far, E. Hallaji, M. Saif, and G. Ditzler <br/>
  IEEE Transactions on Industrial Electronics, 2019, vol. 66, no. 1, pp. 561-570. 
1. [Weight normalization with spiking neural networks](https://www.sciencedirect.com/science/article/pii/S0893608018302508){target="_blank"}<br/>
  Z. Liang, D. Schwartz, G. Ditzler, and O. Ozan Koyluoglu<br/>
  Neural Networks, 2018, vol. 108, pp. 365-378. 
1. [AKRON: An Algorithm for Approximating Sparse Kernel Reconstruction](http://www.sciencedirect.com/science/article/pii/S0165168417303791){target="_blank"}<br/>
  G. Ditzler, N. Bouaynaya, and R. Shterenberg <br />
  Signal Processing, vol. 144, 2018, pp. 265-270.
1. [Improvements to Scalable Online Feature Selection Using Bagging and Boosting](http://ieeexplore.ieee.org/document/8065078/){target="_blank"}<br />
  G. Ditzler, J. LaBarck, J. Ritchie, G. Rosen, and R. Polikar<br/>
  IEEE Transactions on Neural Networks and Learning Systems, 2018. vol. 29, no. 9, pp. 4504-4509
1. [A Sequential Learning Approach for Scaling up Filter-Based Feature Subset Selection](http://ieeexplore.ieee.org/abstract/document/7926436/){target="_blank"}<br/>
  G. Ditzler, R. Polikar, and G. Rosen<br />
  IEEE Transactions on Neural Networks and Learning Systems, 2018, vol. 29, no. 6, pp. 2530-2544.
1. [Fizzy: Feature selection for metagenomics](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0793-8){target="_blank"}<br />
  G. Ditzler, J. Calvin Morrison, Y. Lan, and G. Rosen<br />
  BMC Bioinformatics, 2015, vol 16, no. 358. 
1. [Multi-Layer and Recursive Neural Networks for Metagenomic Classification](http://ieeexplore.ieee.org/document/7219432/){target="_blank"}<br />
  G. Ditzler, R. Polikar, and G. Rosen<br />
  IEEE Transactions on Nanobioscience, 2015, vol. 14, no. 6, pp. 608-616.
1. [Adaptive strategies for learning in nonstationary environments: a survey](http://ieeexplore.ieee.org/document/7296710/){target="_blank"}<br />
  G. Ditzler, M. Roveri, C. Alippi, and R. Polikar<br />
  IEEE Computational Intelligence Magazine, 2015, vol. 10, no. 4, pp. 12-25.  
1. [A bootstrap based Neyman-Pearson test for identifying variable importance](http://ieeexplore.ieee.org/document/6823119/){target="_blank"}<br />
  G. Ditzler, R. Polikar, and G. Rosen<br />
  IEEE Transactions on Neural Networks and Learning Systems, 2015, vol. 26, no. 4, pp. 880-886. 
1. [Incremental learning of concept drift from streaming imbalanced data](http://ieeexplore.ieee.org/document/6235959/){target="_blank"}<br />
  G. Ditzler and R. Polikar<br />
  IEEE Transactions on Knowledge & Data Engineering, 2013, vol. 25, no. 10, pp. 2283–2301.





## Conferences
1. [Boosting Aerial Object Detection Performance via Virtual Reality Data and Multi-Object Training](https://2023.ijcnn.org/) <br/>
   N. Koutsoubis, K. Naddeo, G.  Williams, G. Lecakes, T. Kiel, G.  Ditzler, N. Bouaynaya <br/>
   IEEE/INNS International Joint Conference on Neural Networks, 2023.
1. [DyViR: Dynamic Virtual Reality Dataset for Aerial Threat Object Detection](https://spie.org/dcs23/conferencedetails/synthetic-data-for-machine-learning?SSO=1)<br/>
  N. Koutsoubis, K. Naddeo, G.  Williams, G. Lecakes, A. Almon, T. Kiel, G.  Ditzler, N. Bouaynaya <br/>
  SPIE Defense + Commercial Sensing Meeting Information: Synthetic Data for Artificial Intelligence and Machine Learning: Tools, Techniques, and Applications, 2023. 
1. [On Reducing Adversarial Vulnerability with Data Dependent Stochastic Resonance](https://ieeexplore.ieee.org/abstract/document/10022248/https://ieeessci2022.org/index.html){target="_blank"} <br/>
  D. Schwartz and G. Ditzler<br/>
  IEEE Symposium Series on Computational Intelligence, 2022.  
1. [Application of Adversarial Machine learning in Protocol and Modulation Misclassification](https://www.spiedigitallibrary.org/conference-proceedings-of-spie/12113/121131J/Application-of-adversarial-machine-learning-in-protocol-and-modulation-misclassification/10.1117/12.2619523.full){target="_blank"} <br/>
  M. Krunz, W. Zhang, and G. Ditzler <br/>
  Proceedings of the SPIE, Artificial Intelligence and Machine Learning for Multi-Domain Operations Applications IV, 2022. [[talk](https://www.spiedigitallibrary.org/conference-presentations/12113/0000/Application-of-adversarial-machine-learning-in-protocol-and-modulation-misclassification/10.1117/12.2619523?SSO=1){target="_blank"}]
1. [Targeted Data Poisoning Attacks Against Continual Learning Neural Networks](https://ieeexplore.ieee.org/abstract/document/9892774){target="_blank"} <br/>
  H. Li and G. Ditzler <br/>
  IEEE/INNS International Joint Conference on Neural Networks, 2022.
1. [Inter-Architecture Portability of Artificial Neural Networks and Side Channel Attacks](https://dl.acm.org/doi/abs/10.1145/3526241.3530356){target="_blank"} <br/>
  M. Gopale, G. Ditzler, R. Lysecky and J. Roveda <br/>
  Great Lakes Symposium on VLSI  (GLSVLSI), 2022.
1. [Intelligent Jamming of Deep Neural Network Based Signal Classification for Shared Spectrum](https://ieeexplore.ieee.org/abstract/document/9653072){target="_blank"} <br/>
  W. Zhang, M. Krunz, and G. Ditzler <br/>
  Military Communications Conference (MILCOM), 2021.
1. [Multi-Layer Mapping of Cyberspace for Intrusion Detection](https://ieeexplore.ieee.org/abstract/document/9686823){target="_blank"} <br/>
  S. Shao, P. Satam, S. Satam, K. AI-Awady, G. Ditzler, S. Hariri, and C. Tunc <br/>
  ACS/IEEE International Conference on Computer Systems and Applications, 2021.
1. [Adversarial Filters for Secure Modulation Classification](https://ieeexplore.ieee.org/abstract/document/9723329){target="_blank"} <br/>
  A. Berian, K. Staab, G. Ditzler, T. Bose, and R. Tandon<br/>
  Asilomar Conference on Signals, Systems and Computers, 2021.
1. [Bolstering Adversarial Robustness with Latent Disparity Regularization](https://ieeexplore.ieee.org/abstract/document/9533815){target="_blank"} <br/>
  D. Schwartz and G. Ditzler<br/>
  IEEE/INNS International Joint Conference on Neural Networks, 2021.
1. [OrderNet: Sorting High Dimensional Low Sample Data with Few-Shot Learning](https://ieeexplore.ieee.org/abstract/document/9533766){target="_blank"} <br/>
  S. Hess and G. Ditzler<br/>
  IEEE/INNS International Joint Conference on Neural Networks, 2021.
1. [A Light-Weight Monocular Depth Estimation With Edge-Guided Occlusion Fading Reduction](https://link.springer.com/chapter/10.1007/978-3-030-64559-5_6){target="_blank"} <br/>
  K.-S. Peng, G. Ditzler, and J. Rozenblit<br/>
  International Symposium on Visual Computing, 2020. 
1. [Bypassing Temporal Dependency in Adversarial Audio Examples](https://ieeexplore.ieee.org/abstract/document/9308597){target="_blank"} <br/>
  H. Liu and G. Ditzler<br/>
  IEEE Symposium Series on Computational Intelligence, 2020. 
1. [Detecting Adversarial Audio via Activation Quantization Error](https://ieeexplore.ieee.org/abstract/document/9206986){target="_blank"} <br/>
  H. Liu and G. Ditzler <br/>
  IEEE/INNS International Joint Conference on Neural Networks, 2020.
1. [Self-Supervised Correlational Monocular Depth Estimation using ResVGG Network](https://pdfs.semanticscholar.org/4940/dbf5d2b484e4afa75217ffdc69f73d996b05.pdf){target="_blank"} <br/>
  K.S. Peng, G. Ditzler and J. Rozenblit<br/>
  International Conference on Intelligent Systems and Image Processing, 2019.
1. [Poisoning mRMR with Adversarial Data](https://ieeexplore.ieee.org/document/8683530){target="_blank"} <br/>
  H. Liu and G. Ditzler <br />
  IEEE International Conference on Acoustics, Speech and Signal Processing, 2019.
1. [Online Reconfigurable Antenna State Selection based on Thompson Sampling](https://ieeexplore.ieee.org/document/8685555){target="_blank"} <br/>
  T. Zhao, G. Ditzler, and M. Li <br/>
  International Conference on Computing, Networking and Communications, 2019.
1. [The Impact of an Adversary in a Language Model](https://ieeexplore.ieee.org/abstract/document/8628894/){target="_blank"} <br/>
  Z. Liang and G. Ditzler <br/>
  IEEE Symposium Series on Computational Intelligence, 2018.
1. [Malicious HTML File Prediction: A Detection and Classification Perspective with Noisy Data](https://ieeexplore.ieee.org/abstract/document/8612855/){target="_blank"} <br/>
  S. Hess, P. Satam, G. Ditzler and S. Hariri <br/>
  ACS/IEEE International Conference on Computer Systems and Applications, 2018.
1. [Nonlinear Brain Tumor Model Estimation with Long Short-Term Memory Neural Networks](https://ieeexplore.ieee.org/abstract/document/8489616/){target="_blank"} <br/>
  J. Guo, Z. Liang, E. Scribner, G. Ditzler, N. Bouaynaya and H. Fathallah-Shaykh <br/>
  IEEE/INNS International Joint Conference on Neural Networks, 2018.
1. [Fine Tuning Lasso in an Adversarial Environment Against Gradient Attacks](https://ieeexplore.ieee.org/abstract/document/8280924/){target="_blank"} <br/>
  G. Ditzler and A. Prater <br/>
  IEEE Symposium Series on Computational Intelligence, 2017.
1. [Speeding Up Joint Mutual Information Feature Selection with an Optimization Heuristic](https://ieeexplore.ieee.org/abstract/document/8280921/){target="_blank"} <br/>
  H. Liu and G. Ditzler <br/>
  IEEE Symposium Series on Computational Intelligence, 2017.
1. [Framework to Support DDDAS Decision” Support Systems: Design Overview](http://ieeexplore.ieee.org/abstract/document/8064150/){target="_blank"} <br/>
  G. Ditzler, A. Akoglu, and S. Hariri <br/>
  Workshop on InfoSymbiotics: DDDAS Dynamic Data Driven Applications Systems, 2017.
1. [A Self-Protection Agent using Error Correcting Output Codes to Secure Computers and Applications](http://ieeexplore.ieee.org/abstract/document/8064054/){target="_blank"}  <br/>
  F. de la Pena Montero, S. Hariri, and G. Ditzler <br/>
  IEEE International Conference on Cloud and Autonomic Computing, 2017.
1. [Autonomic Management of 3D Cardiac Simulations](http://ieeexplore.ieee.org/abstract/document/8064049/){target="_blank"} <br/>
  E. Esmaili, A. Akoglu, G. Ditzler, S. Hariri, J. Szep and T. Moukabary <br/>
  IEEE International Conference on Cloud and Autonomic Computing, 2017. (best paper award)
1. [Fraud Analysis Approaches in the Age of Big Data - A Review of State of the Art](http://ieeexplore.ieee.org/abstract/document/8064067/){target="_blank"} <br/>
  S. Makki, R. Haque, Y. Taher, Z. Assaghir, G. Ditzler, M.-S. Hacid and H. Zeineddine <br/>
  International Workshop on Autonomic Systems for Big Data Analytics, 2017.
1. [A Fast Information-theoretic Approximation of Joint Mutual Information Feature Selection](http://ieeexplore.ieee.org/abstract/document/7966441/?reload=true){target="_blank"} <br/>
  H. Liu and G. Ditzler <br/>
  IEEE/INNS International Joint Conference on Neural Networks, 2017.
1. [The AKRON-Kalman Filter for Tracking Time-Varying Networks](http://ieeexplore.ieee.org/abstract/document/7897268/){target="_blank"} <br/>
  V. Carluccio, N. Bouaynaya, G. Ditzler, and H. M. Fathallah Shaykh <br/>
  IEEE International Conference on Biomedical and Health Informatics, 2017.
1. [A Study of Incremental Spectral Meta-Learning for Nonstationary Environments](http://ieeexplore.ieee.org/abstract/document/7727178/){target="_blank"} <br/>
  G. Ditzler   <br/>
  IEEE/INNS International Joint Conference on Neural Networks, 2016.
1. [Scaling a Neyman-Pearson subset selection approach via heuristics for mining massive data ](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=7008701){target="_blank"}<br/>
  G. Ditzler, M. Austen, R, Polikar, and G. Rosen <br/>
  IEEE Symposium on Computational Intelligence in Data Mining, 2014. (travel award) 
1. [Feature Subset Selection for Inferring Relative Importance of Taxonomy](http://dl.acm.org/citation.cfm?id=2660824){target="_blank"} <br/>
  G. Ditzler and G. Rosen <br/>
  ACM International Workshop on Big Data in Life Sciences, 2014. (invited and travel award)
1. [Domain Adaptation Bounds for Multiple Expert Systems Under Concept Drift](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6889909){target="_blank"} <br/>
  G. Ditzler, G. Rosen, and R. Polikar <br/>
  IEEE/INNS International Joint Conference on Neural Networks, 2014. (travel award & best student paper) 
1. [Incremental learning of new classes with unbalanced data](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6706770){target="_blank"} <br/>
  G. Ditzler, G. Rosen, and R. Polikar <br/>
  IEEE/INNS International Joint Conference on Neural Networks, 2013.
1. [Discounted expert weighting for concept drift](http://ieeexplore.ieee.org/document/6595773/?arnumber=6595773){target="_blank"} <br/>
  G. Ditzler, G. Rosen and R. Polikar <br/>
  IEEE International Symposium on Computational Intelligence in Dynamic and Uncertain Environments, 2013.
1. [Information theoretic feature selection for high dimensional metagenomic data](http://ieeexplore.ieee.org/document/6507749/?arnumber=6507749){target="_blank"} <br />
  G. Ditzler, R. Polikar, and G. Rosen <br/>
  IEEE International Workshop on Genomic Signal Processing and Statistics, 2012.
1. [A transductive learning algorithm for concept drift](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6252494){target="_blank"} <br/>
  G. Ditzler, G. Rosen and R. Polikar <br/>
  IEEE/INNS International Joint Conference on Neural Networks, 2012.
1. [Determining significance in metagenomics](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6207004){target="_blank"} <br/>
  G. Ditzler, R. Polikar and G. Rosen <br/>
  IEEE North Eastern Biomedical Engineering Conference, 2012.
1. [Forensic identification with environmental samples](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6288265){target="_blank"} <br/>
  G. Ditzler, R. Polikar, and G. Rosen   <br/>
  IEEE International Conference on Acoustic, Speech and Signal Processing, 2012.
1. [Semi-supervised learning in nonstationary environments](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6033578){target="_blank"} <br/>
  G. Ditzler and R. Polikar <br/>
  IEEE/INNS International Joint Conference on Neural Networks, 2011. (student travel award)
1. [Hellinger distance based drift detection algorithm](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5948491){target="_blank"} <br/>
  G. Ditzler and R. Polikar  <br/>
  IEEE Symposium on Computational Intelligence in Dynamic and Uncertain Environments, 2011.
1. [Fusion methods for boosting performance of speaker identification systems](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5774964){target="_blank"} <br/>
  G. Ditzler, J. Ethridge, R. Polikar, and R. Ramachandran <br/>
  Asia Pacific Conference of Circuits and Systems, 2010.
1. [An incremental learning algorithm for nonstationary environments and imbalanced data](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5597278){target="_blank"} <br/>
  G. Ditzler, R. Polikar, and N. V. Chawla <br/>
  International Conference on Pattern Recognition, 2010.
1. [Optimal $\nu$-SVM parameter estimation using multi-objective evolutionary algorithms](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5586029){target="_blank"} <br/>
  J. Ethridge, G. Ditzler, and R. Polikar <br/>
  IEEE Congress on Evolutionary Computing, 2010.
1. [An ensemble-based incremental learning framework for concept drift and class imbalance](http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5596764){target="_blank"} <br/>
  G. Ditzler and R. Polikar <br/>
  IEEE/INNS International Joint Conference on Neural Networks, 2010.
1. [Incremental learning of new classes in unbalanced data: Learn++.UDNC](https://link.springer.com/chapter/10.1007/978-3-642-12127-2_4){target="_blank"} <br/>
  G. Ditzler, M. Muhlbaier, and R. Polikar <br/>
  International Workshop on Multiple Classifier Systems, 2010.



## Book Chapters  
1. [Analysis Methods for Shotgun Metagenomics](https://link.springer.com/chapter/10.1007/978-3-319-74974-7_5){target="_blank"} <br />
  S. Woloszynek, Z. Zhao, G. Ditzler, J. R. Price, E. R. Reichenberger, Y. Lan, J. Chen, J. Earl, 
  S. Keshani Langroodi, G. Ehrlich and G. Rosen <br />
  Springer Theoretical and Applied Aspects of Systems Biology, 2018, pp. 71–112.
1. [Adaptive classifiers for nonstationary environments](https://onlinelibrary.wiley.com/doi/abs/10.1002/9781119036821.ch7){target="_blank"} <br />
  C. Alippi, G. Boracchi, G. Ditzler, R. Polikar, and M. Roveri <br />
  Contemporary Issues in Systems, Science and Engineering, IEEE/Wiley Press Book Series, 2015.
1. [Variable Selection to Improve Classification of Metagenomes](https://link.springer.com/referenceworkentry/10.1007/978-1-4614-6418-1_364-4){target="_blank"} <br />
  G. Ditzler, Y. Lan, J.-L. Bouchot, and G. Rosen <br />
  In: Nelson K. (eds) Encyclopedia of Metagenomics. Springer, New York, NY, 2014. 
1. [Advances in machine learning for processing and comparison of metagenomic data](https://app.dimensions.ai/details/publication/pub.1030514139){target="_blank"} <br />
  J.-L. Bouchot, W. Trimble, G. Ditzler, Y. Lan, S. Essinger, and G. Rosen <br />
  In: Computational Systems Biology, 295-329, 2014


## Technical Reports 
1. [Review of Automatic Speech Recognition Methodologies](https://rosap.ntl.bts.gov/view/dot/68518){target="_blank"} <br/>
   G. Achour, O. Salunke, A. Payan, E. Harrison, C. Sahbani, G. Carannante, G. Ditzler, N. Bouaynaya <br/>
   United States. Department of Transportation. Federal Aviation Administration. William J. Hughes Technical Center, DOT/FAA/TC-23/47, 2023. 