---
title: "Alumni"
---


## PhD  
- [Samuel Hess](https://www.linkedin.com/in/samuel-hess-143b6175), PhD (2022)
- [Heng Liu](https://www.linkedin.com/in/lh5712/){target="_blank"}, PhD (2021)
- [Kuo-Shiuan Peng](https://www.linkedin.com/in/kuo-shiuan-peng-24360567/){target="_blank"}, PhD (2019)
- [Samuel Hess](https://www.linkedin.com/in/samuel-hess-143b6175/), PhD (2022)

## MSc  
- [Srishti Gupta](https://www.linkedin.com/in/srishtigupta01/){target="_blank"}, MSc (2021)
- [Jiashu Guo](https://www.linkedin.com/in/jiashu-guo/){target="_blank"}, MSc (2018)
- [Zhengzhong Liang](https://www.linkedin.com/in/zhengzhong-liang-095810137/){target="_blank"}, MSc (2018)

## Graduate Interns 
- [Brandon Black](https://www.linkedin.com/in/brandonleeblack/){target="_blank"} (ECE 2019--2020)
- [Sebastian Thiem](https://www.linkedin.com/in/sebastian-thiem-4b25b1159/){target="_blank"} (ECE 2019--2020)
- [Zili Rong](https://www.linkedin.com/in/zili-rong/){target="_blank"} (ECE 2017--2018)
- [Jonathan Gill](https://www.linkedin.com/in/therealjtgill/){target="_blank"} (ECE 2016--2017) 

## Undergraduate @ UArizona
- [Megan Herzog](https://www.linkedin.com/in/megancherzog/){target="_blank"} (CS 2021/22)
- Roman Golota (ECE 2020--2022)
- Drew Howell (CS 2021)
- Eduardo Zambrana (ECE 2020)
- Jack Blake (ECE 2020)
- Javier Cota (ECE 2020/21)
- [Diego Alcantera](https://www.linkedin.com/in/diego-k-alcantara/){target="_blank"} (ECE 2020)
- [Andrew Burger](https://www.linkedin.com/in/andrew-burger-8a628870){target="_blank"} (ECE 2018/19)
- [Noah Thurston](https://www.linkedin.com/in/noah-t-180021b7/){target="_blank"} (ECE 2019)
- Sean Miller (CS/ECE 2017)

## Summer Undergraduate Research Students 

The research experiences for undergraduate students were externally funded by the National Science Foundation and Department of Energy. 

- Christian Hecht (2023; Rowan University)
- Zach Bravo (2023; Rowan University)
- Wyatt Mayor (2022; Monmouth College)
- Ryan Smith (2022; University of Arizona)
- Andrew Wang (2022; Cornell University)
- Gopal Nookula (2022; University of California, Riverside)
- Andres Mendozas (2022; University of Arizona)
- Alex Choi (2022; University of Arizona)
- Ameer Nessaee (2022; University of Arizona)
- Michael Villasana (2022; University of Arizona)
- Derek Lee (2022; University of Arizona)
- Cody Smith (2022; Navajo Technical University)
- Monique Hoswoot (2022; Navajo Technical University)
- [Megan Herzog](https://www.linkedin.com/in/megancherzog) (2021; University of Arizona) ([Summary](){target="_blank"})
- Joe Liang (2021; University of Arizona) ([Summary](){target="_blank"})
- [Sophia Somerscales](https://www.linkedin.com/in/sophiasomerscales/) (2021; University of Arizona) ([presentation](https://www.youtube.com/watch?v=6M8DheHi_2M){target="_blank"})
- [Audrey Wiseman](https://www.linkedin.com/in/audrey-wiseman-59093a172/) (2021; Wofford College) ([presentation](https://www.youtube.com/watch?v=ldJKtB9AFP4){target="_blank"})
- [Issac Wasserman](https://www.linkedin.com/in/isaac-wasserman-63423715a/) (2021; Haverford College) ([presentation](https://www.youtube.com/watch?v=wxLQW90vG-4&t=1s){target="_blank"})
- [Sara Roman](https://www.linkedin.com/in/sara-roman-a24855170/) (2021; Kent State University)  ([presentation](https://www.youtube.com/watch?v=QzdV03hKoNU){target="_blank"})
- Sebastian Valencia (2020; University of Arizona)  ([presentation](){target="_blank"})
- [Ulrich Zongo](https://www.linkedin.com/in/ulrich-stephane-zongo/){target="_blank"} (2020; University of Arizona) ([presentation](){target="_blank"})
- Eduardo Zambrana (2020; University of Arizona) ([presentation](){target="_blank"})
- [Calvin Barrett](https://www.linkedin.com/in/calvin-barrett-293296187/){target="_blank"} (2020; Haverford College) ([presentation](https://www.youtube.com/watch?v=VWeaJDeazUc&feature=youtu.be){target="_blank"})
- [Tomo Bessho](https://www.linkedin.com/in/tbessho/){target="_blank"} (2020; University of Nebraska-Lincoln)  ([presentation](https://www.youtube.com/watch?v=vlJAxQZX9xc&feature=emb_title){target="_blank"})




